# Config file of Snakefile bam2vcf_lite
# modified version of bam2vcf
# BAM from external pipelines (mapache, generode...) as input
# Load environment from within jonasl environment with $ conda activate bam2vcf

metadata: /media/labgenoma4/DATAPART4/jonasl/data/tigrinus/generode/metadata/subs_dp1.8_metadata_2024FEB28.tsv
exclude: []

ref:
    species: "Leopardus geoffroyi"
    assembly: "Oge1_edited"
    contig_tag: "scaffold"
    MT: "MT"
    sex_chr: ["X"]
    file: /media/labgenoma4/DATAPART7/duda_grupo/references/O.geoffroyi_Oge1_pat1.0/O.geoffroyi_Oge1_pat1.0_genomic_edited.fasta
    repeatmasker_out: /media/labgenoma4/DATAPART7/duda_grupo/references/Lge_Assembly_v1/Lge-1_final_rm.out.gz

outgroup: []

bootstraps: 1000

input:
    bam: /media/labgenoma4/DATAPART4/jonasl/data/tigrinus/generode/subs_dp1.8 

output:
    vcf: /media/labgenoma4/DATAPART4/jonasl/data/tigrinus/vcf_Oge1

bin:
    variantqc: /media/labgenoma4/DATAPART4/jonasl/bin/DISCVRSeq/DISCVRSeq-1.3.9.jar
    vcf2dis: /media/labgenoma4/DATAPART4/jonasl/bin/VCF2Dis/bin/VCF2Dis
    fastme: /media/labgenoma4/DATAPART4/jonasl/bin/FastME/binaries/fastme-2.1.6.2-linux64
    vcf2phylip: /media/labgenoma4/DATAPART4/jonasl/bin/vcf2phylip/vcf2phylip.py

scripts:
    plot_plink_pca: /media/labgenoma4/DATAPART4/jonasl/scripts/plot_plink_pca.py

